//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _221_Puzacheva_AdService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int ID { get; set; }
        public System.DateTime Publication_date { get; set; }
        public int City { get; set; }
        public int User_ID { get; set; }
        public int Category { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Photo { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual City City1 { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Type Type1 { get; set; }
        public virtual User User { get; set; }
    }
}
